/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#41474f",
        "surface-tint": "#236391",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#96ccff",
        "tertiary-container": "#d89d00",
        "tertiary": "#7b5800",
        "primary": "#236391",
        "on-tertiary-fixed": "#271900",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffdea6",
        "surface-container": "#eeeeee",
        "inverse-on-surface": "#f0f1f1",
        "surface-container-high": "#e8e8e8",
        "secondary-fixed-dim": "#c6c6c6",
        "on-tertiary-fixed-variant": "#5d4200",
        "on-surface": "#1a1c1c",
        "on-tertiary-container": "#503800",
        "on-secondary-fixed-variant": "#474747",
        "secondary-fixed": "#e2e2e2",
        "on-primary-fixed-variant": "#004a75",
        "surface-dim": "#dadada",
        "surface-container-highest": "#e2e2e2",
        "outline": "#717880",
        "background": "#f9f9f9",
        "surface-variant": "#e2e2e2",
        "inverse-primary": "#96ccff",
        "on-secondary-container": "#646464",
        "on-secondary": "#ffffff",
        "on-primary-container": "#003f65",
        "surface-bright": "#f9f9f9",
        "secondary-container": "#e2e2e2",
        "on-primary": "#ffffff",
        "on-background": "#1a1c1c",
        "on-error": "#ffffff",
        "primary-fixed": "#cee5ff",
        "tertiary-fixed-dim": "#febb1b",
        "on-tertiary": "#ffffff",
        "surface": "#f9f9f9",
        "on-secondary-fixed": "#1b1b1b",
        "on-error-container": "#93000a",
        "secondary": "#5e5e5e",
        "primary-container": "#74acdf",
        "outline-variant": "#c1c7d0",
        "surface-container-low": "#f3f3f4",
        "inverse-surface": "#2f3131",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#001d32"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Be Vietnam Pro", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
